from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Confidence(str, Enum):
    high = "high"
    medium = "medium"
    low = "low"


class Source(str, Enum):
    input = "input"
    inferred = "inferred"
    llm = "llm"  # generated by a real model call (see app/llm/ollama_client.py), not a rule


class Severity(str, Enum):
    info = "info"
    warning = "warning"
    error = "error"


class RawProductIn(BaseModel):
    """Mirrors the real Unilog raw catalog schema exactly (6 columns)."""

    mfg_part_num: str
    part_desc: str
    e1_brand: Optional[str] = None
    unilog_brand: Optional[str] = None
    dib_brand: Optional[str] = None
    part_manuf: str


class EnrichedField(BaseModel):
    value: str
    confidence: Confidence
    source: Source
    rationale: str


class Attribute(BaseModel):
    label: str
    value: str
    uom: Optional[str] = None
    confidence: Confidence
    source: Source
    rationale: str
    lov_compliant: Optional[bool] = None  # None = no fixed vocabulary (measured value)


class ValidationFlag(BaseModel):
    field: str
    issue: str
    severity: Severity


class EnrichedProduct(BaseModel):
    id: Optional[int] = None

    raw_mfg_part_num: str
    raw_part_desc: str
    raw_part_manuf: str

    manufacturer_name: EnrichedField
    brand_name: EnrichedField
    classpath: EnrichedField

    invoice_desc: EnrichedField  # <=40 char, CAPS
    mobile_desc: EnrichedField  # 60-80 char
    short_desc: EnrichedField  # product title
    long_desc: EnrichedField

    attributes: list[Attribute] = Field(default_factory=list)

    validation_flags: list[ValidationFlag] = Field(default_factory=list)
    status: str = "pending"  # pending | reviewed
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ProductPatch(BaseModel):
    manufacturer_name: Optional[str] = None
    brand_name: Optional[str] = None
    classpath: Optional[str] = None
    invoice_desc: Optional[str] = None
    mobile_desc: Optional[str] = None
    short_desc: Optional[str] = None
    long_desc: Optional[str] = None
    attributes: Optional[dict[str, str]] = None  # label -> new value
    status: Optional[str] = None
